### ISSUE TITLE
Extraneous call to jscript causes compatibility problems

### ISSUE THREAD

**Issue by mc12345678** [potteryhouse/stock_by_attribute_1.5.4#22]
As identified at: http://www.zen-cart.com/showthread.php?p=1268798#post1268798 by karinvd a problem was identified when SBA and zen-colorbox were installed together on a ZC 1.5.4 install (version higher than for which this has been specifically targeted).

It was later identified (Diva Vocals) and tested (karinvd) to remove the src=specific javascript call from line 42 of includes/functions/extra_functions/products_with_attributes.php to read:

$field = '<script type="text/javascript">
	 			$(function(){
					$("#attrib-'.$tmp_attribID.'").on("click", function(){
						$("#SBA_ProductImage").attr("src", $(this).find(":selected").attr("data-src"));
					});
				});
	   </script>';

Suggest verification that incorporation of this change will allow the code to function and to incorporate the change here as well as in SBA 1.5.3.

Problem observed was that the image would not load with these two plugins installed together. (I have not tested this image functionality regardless of installed with or without zen_colorbox.)

**Comment by potteryhouse** [comment]
We need to update all the jquery code to use the newly included version now supported in Zen Cart 1.5.4.
The jquery version incuded by default in the common template is 1.11.x.
zen-cart-v1.5.4-12302014\includes\templates\template_default\jscript

We should no longer need to "include" any other version of jquery, and we need to see if the file jquery.form.js is still needed or not.

**Comment by mc12345678** [comment]
Can't say that I've tried removing jquery.form.js but by making some other changes have incorporated the necessary revisions to support jQuery v1.11.1 (as seen necessary).  Thinking of cleaning this up to be a single issue to address as a new issue #33.
