### ISSUE TITLE
Can't update inventory

### ISSUE THREAD

**Issue by jeking928** [potteryhouse/stock_by_attribute_1.5.4#24]
When updating the inventory from the admin for an attribute, zero inventory is the result in all cases.

My test was a mixed attribute, but probably applies to all.

**Comment by mc12345678** [comment]
Clarification to the above based on reported issue:
When initially populating the variants to include quantity, if the quantity was set to 0 the variant was not added; however, if the quantity was a non-zero value, the variant would be added.  Once added, adjustment of the variant quantity to zero was successfully saved.

There may be/may have been a system response difference of using the update quantities button as compared to the javascript for updating in place... but issue #23 has been updated to address assignment of the quantity using the float variable method provided by the ZC $db queryfactory class.

**Comment by jeking928** [comment]
I think we are actually talking about different issues. I was not very clear in my initial comment, sorry.  There are a few ways to update inventory.  The one I *meant* was when clicking on Edit Quantity from products_with_attributes_stock.php This open a new page. Entering any value on this page results in the inventory being set to zero.

**Comment by mc12345678** [comment]
Yup, sure were talking about two different things. Edit of quantity has been corrected in branch. Don't like the temporary solution, but can more accurately correct it in next upload. Data is being provided as a data type double that is converted to 0 when sent off for processing as a "float"...  By changing the datatype to passthru in the query, whatever is provided (confirmed to be numeric and of some value) is sent on to mysql... As said works, but the data type should have been possibly cast as a float to begin with.

**Comment by mc12345678** [comment]
Both issues resolved in #23. Able to enter partial quantities and they stick through both individual variant edit, direct edit on screen and save. 

Also issue of adding a new variant with a quantity of 0 is corrected.

Closing this issue. Code "improvements" are not an "issue".
