### ISSUE TITLE
Readme and Instructions files issues

### ISSUE THREAD

**Issue by Mikeondraco** [potteryhouse/stock_by_attribute_1.5.4#28]
At mc12345678's request after making comments elsewhere I have been looking at the SBA Readme docs. The zip file downloads OK and unzips as expected. The main readme doc opens and is concise and informative. However, the link within that document to the user Instructions does not function here, the path to the 'Temp' directory not being accessible (or even present at times).

This, of course, may be an issue with my Op system installation here, but I get the same problem on this laptop and another desktop. Both computers are running Win 8.1 with the most up-to-date security patches.

If it is thought to be a problem here then I apologise for raising this, but if not, perhaps the developers are not aware. If I can be of any help, limited as this may be as I am more a user than a developer, please do not hesitate to ask.

Regards ... Mike

**Comment by mc12345678** [comment]
Copied/moved to the Readme and Instructions issues thread... That way the issues remain within/associated with the applicable topic.

https://github.com/potteryhouse/stock_by_attribute_1.5.X_Instructions/issues/1
Closing the comment here as it is applicable to address there...
