### ISSUE TITLE
Read only option names are incorporated in SBA variants.

### ISSUE THREAD

**Issue by mc12345678** [potteryhouse/stock_by_attribute_1.5.4#31]
While testing the use of Read Only option names, it was identified that Read Only option names are included in the variant list/determination. Read only option names have no effect on stock as they are displayed only and have/take no user interaction. They should not be displayed for variant creation, nor used anywhere in stock quantity determination as a result.

That is unless someone can identify a reason/need/use of them in stock determination...

Thoughts on resolution, either determine upon attribute review that the attribute is read only and take appropriate action, or in incorporation of new table data of attributes that should not be used in calculation that read only attributes are so marked to prevent downstream use/calculation.

Ideally, some centralized function could be used to capture this action to prevent incomplete incorporation throughout the code.

**Comment by mc12345678** [comment]
Ideas to address this:
Add function (sql) to remove readonly attributes from created variants.
Provide indication in admin panel when generating variants of which attributes are readonly with accompaning description of effect of adding to a combination variant (at least until this is otherwise resolved).
In evaluation of product provide some form of check to omit readonly attributes from stock quantities until some need or alternate flag is identified/incorporated.
Additional action to be determined/identified. Ideas?

**Comment by wiztechinc** [comment]
Though I can certainly use the remove function now, definitely the check for read only first in the scripts would be a best way. Having to run a function to remove what was done by another script is not cool. I don't know how the script works now but simply excluding the read only attributes at first makes sense. I can't think how someone would ever need stock for readonly .

**Comment by mc12345678** [comment]
So, just thought of a few things. One the attribute of a product could be changed to readonly or from readonly which would mean checks are necessary at that level/location. Ideally in that regards, the attribute would always be recognized with the product, but would be of no consequence if it were filtered out/added into the listing as necessary for the comparison(s)

As for stock of readonly, well I could see someone using it as their token of say this extra object comes free with this... Plus there are some goals of trying to expand functionality of this to the maximum conceivable so ideally don't want to boot anything out of consideration ideally.

Am also considering with the above in mind, adding some of the script features to be independently applied to individual product. I know one that I'd like to see just because of doing testing is a delete all variants for a product option... Afterall, there's a create, so should have a delete for the same. (I think)

I have a concept in mind for the delete all read only. 

Using the sql for the add all which identifies product plus attribute, remove the associated attribute_id from all rows with that attribute, then cleanup by removing any pre/post commas and replace double commas with single and if a variant has no attribute_id remaining to delete the variant. Do for all such attributes identified and done.

Thing is on the search of rows with the attribute_id going to have to use the same style of query I did elsewhere, looking for cases that begin with the attribute_id, end with it, have a comma on each side of it, and are in alone... Seems taxing on the server, but...

Seems to me to be yet another reason to reconsider the table structure of tracking the applicable attributes for stock...

**Comment by wiztechinc** [comment]
database table really needs redoing - the biggest problem with this thing always

**Comment by mc12345678** [comment]
So, I'd figured this out once before, but at the time hadn't done anything about it. But, the sql in the install section incorrectly refers to "read-only" when actually it is addressing "display-only" attributes. That is something different. Anyways, if an attribute is marked as display only (what I would recommend for your read-only attributes, though not required by default ZC) then they are not to appear as options for the selection in the basic generation. Didn't see that before so need to verify incorporated into the combo version of creating variants.  Anyways, for those that have added a read-only attribute and not marked it as display only in the attributes controller, there is now a remove read-only option in the admin->configuration for SBA. It will remove read-only attributes from the list of attributes needed to purchase the item. If in removal a product is generated that has the same products_id and same stock_attributes as an existing product, then the stock_id of the current product is deleted.

**Comment by mc12345678** [comment]
Have made READONLY attributes as not a part of being a stockable quantity.  Code will exist as part of a download when this issue is closed (by upload/inclusion of the code changes); however, at this time, Dynamic Dropdowns does not recognize them, so if there are two or more attributes and Dynamic Dropdowns is active, dynamic dropdowns will not display if there is a Readonly attribute assigned to the product.  This means that the "html" presentation of the available stock of the item will not be presented next to the selection; however, the addition of the quantity of product will be rejected if it exceeds the SBA available quantity.

**Comment by mc12345678** [comment]
Incorporated into https://github.com/mc12345678/Stock_By_Attributes_Combined/
as of 
https://github.com/mc12345678/Stock_By_Attributes_Combined/commit/e991db49db42c0cb54246e54558d0c26397d0ecc
